# Sample batch script


algorithms=gfall, neighborcf_itembased

trainingsets=datasets/movielens/hdp_rating1.base#snapshot_parser#file, datasets/movielens/hdp_rating2.base#snapshot_parser#file, datasets/movielens/hdp_rating3.base#snapshot_parser#file, datasets/movielens/hdp_rating4.base#snapshot_parser#file, datasets/movielens/hdp_rating5.base#snapshot_parser#file

testingsets=datasets/movielens/hdp_rating1.test#snapshot_parser#file, datasets/movielens/hdp_rating2.test#snapshot_parser#file, datasets/movielens/hdp_rating3.test#snapshot_parser#file, datasets/movielens/hdp_rating4.test#snapshot_parser#file, datasets/movielens/hdp_rating5.test#snapshot_parser#file
